
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200 ; Wichtig, da ESP32 meist schneller kommuniziert als der Nano
lib_deps = 
    lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5